kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-1
  labels:
    app: postgres
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-postgres-pv-claim
  labels:
    app: user-postgres
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hostpath
  resources:
    requests:
      storage: 3Gi