apiVersion: v1
kind: ConfigMap
metadata:
  name: user-postgres-config
  labels:
    app: user-postgres
data:
  TZ: Asia/Singapore
  POSTGRES_DB: registry
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-postgres-init-script
data:
  init.sql: |-
    CREATE TABLE "user" (
    	user_id SERIAL PRIMARY KEY NOT NULL,
        username VARCHAR (255) UNIQUE NOT NULL,
        password VARCHAR (255) UNIQUE NOT NULL,
        salt VARCHAR (255) UNIQUE NOT NULL,
    	creation_time timestamp default CURRENT_TIMESTAMP,
        update_time timestamp  default CURRENT_TIMESTAMP,
        deleted boolean DEFAULT false NOT NULL
    );