apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: user-api
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: user-api
      tier: server
  template:
    metadata:
      labels:
        run: user-api
        tier: server
    spec:
      containers:
        - name: user-api
          image: registry.gitlab.com/be-devops-tranning/user-service/server:prod
          imagePullPolicy: Always
          env:
            - name: POSTGRESQL_HOST
              value: "user-postgres"
            - name: REDIS_URL
              value: "redis-svc"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: gitlab-key
